###############################################################################
# build.tcl -- project, block design, bitstream.
#
#   vivado -mode batch -source tcl/build.tcl -tclargs \
#          <srcs.f> <part> <board> <out_dir> <defines> <incdirs> \
#          <fclk_mhz> <mem_backend> <mem_kb> <trace> <stage>
#
# stage is one of:
#   bd        stop after the block design validates -- minutes, and it is where
#             almost every mistake in bd_pynq.tcl shows up
#   synth     stop after synthesis
#   bit       through implementation to a bitstream + .hwh
#
# `bd` exists because the block design is the part of this flow that fails, and
# waiting an hour through synthesis to find out that an interface did not infer
# is a bad way to spend an afternoon.
###############################################################################

if {[llength $argv] < 12} {
    puts "ERROR: expected 12 tclargs, got [llength $argv]"
    exit 1
}
lassign $argv srcs_f part board out_dir defines incdirs \
              fclk_mhz mem_backend mem_kb trace stage board_repo

if {$board eq "none" && $stage eq "bit"} {
    puts "ERROR: board=none produces a design with Vivado's default PS7 settings,"
    puts "       not the PYNQ-Z2's DDR part, timing or MIO map.  A bitstream from"
    puts "       it cannot bring up memory.  Use it with stage 'bd' or 'synth' to"
    puts "       check the design's structure, and install the board files before"
    puts "       building anything you intend to program."
    exit 1
}

set script_dir [file dirname [file normalize [info script]]]
set proj_dir   [file join $out_dir proj]

puts "=== amoeba PYNQ-Z2 build ==="
puts "  part       : $part"
puts "  board      : $board"
puts "  backend    : $mem_backend  (${mem_kb} KiB)"
puts "  trace      : $trace"
puts "  fclk       : $fclk_mhz MHz"
puts "  stage      : $stage"
puts "  out        : $out_dir"

file mkdir $out_dir
create_project -force amoeba $proj_dir -part $part

# Board files live wherever the user put them.  Setting the repo path keeps them
# out of the Vivado install, which matters when the install is a shared one and
# when the next person to build this needs to know where they came from.
if {$board_repo ne "" && $board_repo ne "none"} {
    set_param board.repoPaths $board_repo
    puts "  board repo : $board_repo"
}

# ---- sources ---------------------------------------------------------------
# The same filelist the utilization gate uses, generated by the Makefile from
# the same find(1) the simulation build uses.  One list, three consumers.
set fh [open $srcs_f r]
set srcs [split [string trim [read $fh]] "\n"]
close $fh
add_files -norecurse $srcs
set_property file_type SystemVerilog [get_files *.sv]

# Header files have to be IN the project, not merely on the include path.
# Synthesis is happy with -include_dirs alone; IPI's module-reference
# elaboration is not, and says so as
#   [filemgmt 56-591] Given include File '...' needs to be addded to the
#   project in order to use it as an RTL module
# which is easy to misread as a missing file rather than a missing add_files.
set headers {}
foreach d $incdirs {
    foreach f [glob -nocomplain [file join $d *.vh]] { lappend headers $f }
}
if {[llength $headers]} {
    add_files -norecurse -fileset sources_1 $headers
    # These MUST stay "Verilog Header".  Marking them SystemVerilog silences the
    # prescan warnings described below, and breaks the build: Vivado then
    # compiles them as standalone source files, and config-shared.vh on its own
    # has no idea what VIRTMEM_SUPPORTED or SV39_SUPPORTED are -- those come
    # from the config.vh included ahead of it in the real compilation unit.
    # The failure surfaces much later, in the block design's module-reference
    # synthesis run, as
    #   ERROR: [Synth 8-36] 'VIRTMEM_SUPPORTED' is not declared
    #   ERROR: [Synth 8-439] module 'amoeba_dut_0' not found
    # which reads like a missing module rather than a mis-typed header.
    #
    # The cost of doing it correctly is that Vivado prescans header files for
    # module definitions using a Verilog-2001 parser, so every unsized literal
    # in config-shared.vh and parameter-defs.vh logs an [HDL 9-1206] syntax
    # error as a CRITICAL WARNING.  Those are expected and harmless.  Do not
    # "fix" them by changing the file type: that trades a working build for a
    # quiet log.
    set_property file_type {Verilog Header} \
        [get_files -of_objects [get_filesets sources_1] *.vh]
    puts "  headers    : [llength $headers] .vh files added to the project"
}

set_property include_dirs   $incdirs [current_fileset]
set_property verilog_define $defines [current_fileset]
# Synthesis and the block design's own module-reference elaboration are separate
# filesets, and the config `define is what selects the whole core.  Setting only
# the synthesis one gives a block design elaborated against pkg/config.vh and a
# netlist built from the pruned config -- a mismatch that surfaces as port width
# errors deep in the BD.
set_property include_dirs   $incdirs [get_filesets sources_1]
set_property verilog_define $defines [get_filesets sources_1]

update_compile_order -fileset sources_1

# ---- block design ----------------------------------------------------------
source [file join $script_dir bd_pynq.tcl]

if {![amoeba_build_bd \
        top         amoeba_pynq_top_v \
        board       $board \
        fclk_mhz    $fclk_mhz \
        mem_backend $mem_backend \
        mem_kb      $mem_kb \
        trace       $trace]} {
    puts "ERROR: block design could not be built"
    exit 1
}

set bd_file [get_files amoeba.bd]
make_wrapper -files $bd_file -top -import

set_property top amoeba_wrapper [current_fileset]
update_compile_order -fileset sources_1

# ---- constraints -----------------------------------------------------------
add_files -fileset constrs_1 -norecurse \
    [file join $script_dir .. constraints pynq-z2.xdc]

if {$stage eq "bd"} {
    puts "=== block design validated; stopping at stage 'bd' ==="
    exit 0
}

# ---- synthesis -------------------------------------------------------------
launch_runs synth_1 -jobs 8
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    puts "ERROR: synthesis failed -- see $proj_dir/amoeba.runs/synth_1"
    exit 1
}

if {$stage eq "synth"} {
    open_run synth_1
    report_utilization -file [file join $out_dir utilization.rpt]
    report_timing_summary -file [file join $out_dir timing.rpt]
    puts "=== synthesized; stopping at stage 'synth' ==="
    exit 0
}

# ---- implementation --------------------------------------------------------
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    puts "ERROR: implementation failed -- see $proj_dir/amoeba.runs/impl_1"
    exit 1
}

open_run impl_1
report_utilization        -file [file join $out_dir utilization.rpt]
report_timing_summary     -file [file join $out_dir timing.rpt]

set wns [get_property SLACK [get_timing_paths -delay_type max -max_paths 1]]
puts "  post-route WNS : $wns ns"
if {$wns < 0} {
    puts "WARNING: timing not met.  The bitstream exists but the design will not"
    puts "         run reliably at $fclk_mhz MHz.  Lower FCLK_MHZ and rebuild."
}

# ---- outputs ---------------------------------------------------------------
# The .bit and the .hwh together are what PYNQ's Overlay() wants, and it insists
# they share a basename and sit in the same directory.
set bit [glob -nocomplain [file join $proj_dir amoeba.runs impl_1 *.bit]]
if {[llength $bit]} {
    file copy -force [lindex $bit 0] [file join $out_dir amoeba.bit]
}
set hwh [glob -nocomplain [file join $proj_dir amoeba.gen sources_1 bd amoeba hw_handoff amoeba.hwh]]
if {[llength $hwh]} {
    file copy -force [lindex $hwh 0] [file join $out_dir amoeba.hwh]
} else {
    puts "WARNING: no .hwh found; PYNQ's Overlay() will not be able to load this"
}

puts "=== done: $out_dir/amoeba.bit ==="
exit 0
