###############################################################################
# synth_ooc.tcl -- out-of-context synthesis for the utilization gate.
#
# Answers three questions and nothing else:
#   1. Does the design fit an XC7Z020?
#   2. What clock will it close at?
#   3. Where is the area, so the cache decision has numbers behind it?
#
# Out-of-context means no I/O buffers are inserted and no board constraints are
# needed -- the ports of amoeba_soc_wrapper stay internal nets.  That is what we
# want here: the number should describe the design, not the pin planning, and it
# means this runs with no block design and no bitstream.
#
# Invoked by the Makefile:
#   vivado -mode batch -source synth_ooc.tcl -tclargs \
#          <srcs.f> <top> <part> <period_ns> <report_dir> <defines> <incdirs> \
#          <clk_port> <rst_port>
#
# clk_port and rst_port are passed rather than assumed because the two tops name
# them differently (clk/reset_ext on the DUT, aclk/aresetn on the PL top).  That
# is not a cosmetic detail: create_clock on a port that does not exist is only a
# CRITICAL WARNING, so Vivado will happily synthesize the whole design with NO
# clock constraint at all, report an empty WNS, and exit 0.  The area number
# from such a run is not timing-driven and the timing number does not exist.
# This script therefore checks the port after synthesis and fails hard.
###############################################################################

if {[llength $argv] < 9} {
    puts "ERROR: expected 9 tclargs, got [llength $argv]"
    exit 1
}

lassign $argv srcs_f top part period_ns report_dir defines incdirs clk_port rst_port

puts "=== amoeba OOC synthesis ==="
puts "  top        : $top"
puts "  part       : $part"
puts "  period     : $period_ns ns  ([format %.1f [expr {1000.0/$period_ns}]] MHz)"
puts "  defines    : $defines"
puts "  clock port : $clk_port"
puts "  reset port : $rst_port"
puts "  reports    : $report_dir"

file mkdir $report_dir

# ---- sources ---------------------------------------------------------------
# One list, generated by the Makefile from the same find(1) the simulation
# build uses, so the two cannot drift.  Order matters: packages first.
set fh [open $srcs_f r]
set srcs [split [string trim [read $fh]] "\n"]
close $fh

puts "  sources    : [llength $srcs] files"
read_verilog -sv $srcs

# ---- constraints -----------------------------------------------------------
# Read before synth_design so synthesis is timing-driven rather than having the
# clock applied to a finished netlist afterwards.
set xdc [file join $report_dir ooc.xdc]
set fh [open $xdc w]
puts $fh "create_clock -period $period_ns -name $clk_port \[get_ports $clk_port\]"
# The reset is asynchronous and synchronized inside the design, so its own
# arrival is not a timing path worth reporting.
puts $fh "set_false_path -from \[get_ports $rst_port\]"
close $fh
read_xdc -mode out_of_context $xdc

# ---- synthesize ------------------------------------------------------------
set define_args {}
foreach d $defines {
    if {$d ne ""} { lappend define_args $d }
}

set synth_cmd [list synth_design -top $top -part $part -mode out_of_context]
if {[llength $define_args]} {
    lappend synth_cmd -verilog_define $define_args
}
if {[llength $incdirs]} {
    lappend synth_cmd -include_dirs $incdirs
}

puts "  running    : $synth_cmd"
eval $synth_cmd

# ---- reports ---------------------------------------------------------------
report_utilization              -file $report_dir/utilization.rpt
report_utilization -hierarchical -hierarchical_depth 3 \
                                -file $report_dir/utilization_hier.rpt
report_timing_summary -delay_type max -max_paths 10 \
                                -file $report_dir/timing.rpt
report_timing -delay_type max -max_paths 20 -sort_by group \
                                -file $report_dir/timing_paths.rpt

# A checkpoint so a follow-up run can go straight to place-and-route without
# re-synthesizing -- post-synthesis utilization is an estimate, and the honest
# number for "does it fit" comes after placement.
write_checkpoint -force $report_dir/post_synth.dcp

# ---- machine-readable summary ----------------------------------------------
# Read straight off report_utilization rather than counting cells.  Counting via
# get_cells -filter {PRIMITIVE_GROUP == ...} looks tidier and is wrong: the group
# names are not stable across Vivado releases, and a name that does not match
# returns an EMPTY LIST, not an error -- so BLOCKRAM and ARITHMETIC silently
# reported 0 BRAM and 0 DSP for a design that used 8 and 16 of them.  A fit
# verdict that quietly reads zero for a resource is worse than no verdict.
#
# These are the same rows a human reads off the report, so the table and the
# report can never disagree.  "Block RAM Tile" is already in tiles, which is the
# unit the XC7Z020's 140 is quoted in.
proc util_used {text name} {
    foreach line [split $text "\n"] {
        set l [string trim $line]
        if {![string match "|*" $l]} { continue }
        set f [split $l "|"]
        if {[llength $f] < 4} { continue }
        set site [string trim [string trimright [string trim [lindex $f 1]] "*"]]
        if {$site eq $name} { return [string trim [lindex $f 2]] }
    }
    return 0
}

# The clock has to exist, or every number below describes an unconstrained
# design.  create_clock only warns, so this is where that gets caught.
if {[llength [get_ports -quiet $clk_port]] == 0} {
    puts "ERROR: top '$top' has no port '$clk_port' -- the design was synthesized"
    puts "       with no clock constraint, so its area is not timing-driven and"
    puts "       its WNS does not exist.  Pass the right CLK_PORT."
    exit 1
}
if {[llength [get_clocks -quiet]] == 0} {
    puts "ERROR: no clocks in the design after synthesis; constraints did not apply."
    exit 1
}

set util       [report_utilization -return_string]
set slice_luts [util_used $util "Slice LUTs"]
set slice_regs [util_used $util "Slice Registers"]
set dsps       [util_used $util "DSPs"]
set brams      [util_used $util "Block RAM Tile"]
set paths      [get_timing_paths -quiet -delay_type max -max_paths 1]
if {[llength $paths] == 0} {
    puts "ERROR: no timing paths found; refusing to write a summary with no WNS."
    exit 1
}
set wns        [get_property SLACK [lindex $paths 0]]

set fh [open $report_dir/summary.txt w]
puts $fh "part        $part"
puts $fh "period_ns   $period_ns"
puts $fh "luts        $slice_luts"
puts $fh "regs        $slice_regs"
puts $fh "dsps        $dsps"
puts $fh "brams       $brams"
puts $fh "wns_ns      $wns"
close $fh

puts "=== done: $report_dir/summary.txt ==="
exit 0
